-- Migration 039: Fix Arabic display_name values (corrupted by PowerShell encoding in 038)
BEGIN;

UPDATE permissions SET display_name = 'عرض لوحة القيادة'               WHERE name = 'Dashboard.Overview.View';
UPDATE permissions SET display_name = 'عرض إيرادات الشهر'              WHERE name = 'Dashboard.Revenue.View';
UPDATE permissions SET display_name = 'عرض إحصاءات العمليات'           WHERE name = 'Dashboard.Operations.View';
UPDATE permissions SET display_name = 'عرض الصحة المالية'              WHERE name = 'Dashboard.Financial.View';
UPDATE permissions SET display_name = 'عرض مخزون ومشتريات'             WHERE name = 'Dashboard.Inventory.View';
UPDATE permissions SET display_name = 'لوحة التحكم التنفيذية'          WHERE name = 'Dashboard.Executive.View';

UPDATE permissions SET display_name = 'عرض المرضى'                     WHERE name = 'Patients.Patients.View';
UPDATE permissions SET display_name = 'إضافة مريض'                     WHERE name = 'Patients.Patients.Create';
UPDATE permissions SET display_name = 'تعديل مريض'                     WHERE name = 'Patients.Patients.Edit';
UPDATE permissions SET display_name = 'حذف مريض'                       WHERE name = 'Patients.Patients.Delete';
UPDATE permissions SET display_name = 'طباعة ملف مريض'                 WHERE name = 'Patients.Patients.Print';
UPDATE permissions SET display_name = 'تصدير قائمة المرضى Excel'       WHERE name = 'Patients.Patients.ExportExcel';
UPDATE permissions SET display_name = 'تصدير قائمة المرضى PDF'         WHERE name = 'Patients.Patients.ExportPdf';

UPDATE permissions SET display_name = 'عرض المواعيد'                   WHERE name = 'Appointments.Appointments.View';
UPDATE permissions SET display_name = 'حجز موعد'                       WHERE name = 'Appointments.Appointments.Create';
UPDATE permissions SET display_name = 'تعديل موعد'                     WHERE name = 'Appointments.Appointments.Edit';
UPDATE permissions SET display_name = 'حذف موعد'                       WHERE name = 'Appointments.Appointments.Delete';
UPDATE permissions SET display_name = 'إعادة جدولة موعد'               WHERE name = 'Appointments.Appointments.Reschedule';
UPDATE permissions SET display_name = 'إلغاء موعد'                     WHERE name = 'Appointments.Appointments.Cancel';
UPDATE permissions SET display_name = 'طباعة مواعيد'                   WHERE name = 'Appointments.Appointments.Print';
UPDATE permissions SET display_name = 'عرض طابور الانتظار'             WHERE name = 'Appointments.Queue.View';
UPDATE permissions SET display_name = 'إضافة للطابور'                  WHERE name = 'Appointments.Queue.Create';
UPDATE permissions SET display_name = 'تعديل الطابور'                  WHERE name = 'Appointments.Queue.Edit';
UPDATE permissions SET display_name = 'إزالة من الطابور'               WHERE name = 'Appointments.Queue.Delete';

UPDATE permissions SET display_name = 'مساحة الطبيب'                   WHERE name = 'Clinical.Workspace.View';
UPDATE permissions SET display_name = 'عرض خطط العلاج'                 WHERE name = 'Clinical.TreatmentPlans.View';
UPDATE permissions SET display_name = 'إنشاء خطة علاج'                 WHERE name = 'Clinical.TreatmentPlans.Create';
UPDATE permissions SET display_name = 'تعديل خطة علاج'                 WHERE name = 'Clinical.TreatmentPlans.Edit';
UPDATE permissions SET display_name = 'حذف خطة علاج'                   WHERE name = 'Clinical.TreatmentPlans.Delete';
UPDATE permissions SET display_name = 'اعتماد خطة علاج'                WHERE name = 'Clinical.TreatmentPlans.Approve';
UPDATE permissions SET display_name = 'طباعة خطة علاج'                 WHERE name = 'Clinical.TreatmentPlans.Print';
UPDATE permissions SET display_name = 'عرض مخطط الأسنان'               WHERE name = 'Clinical.DentalChart.View';
UPDATE permissions SET display_name = 'تحديث مخطط الأسنان'             WHERE name = 'Clinical.DentalChart.Edit';
UPDATE permissions SET display_name = 'عرض الإجراءات السريرية'          WHERE name = 'Clinical.Procedures.View';
UPDATE permissions SET display_name = 'إضافة إجراء سريري'              WHERE name = 'Clinical.Procedures.Create';
UPDATE permissions SET display_name = 'تعديل إجراء سريري'              WHERE name = 'Clinical.Procedures.Edit';
UPDATE permissions SET display_name = 'حذف إجراء سريري'                WHERE name = 'Clinical.Procedures.Delete';
UPDATE permissions SET display_name = 'عرض ملفات المريض'               WHERE name = 'Clinical.Files.View';
UPDATE permissions SET display_name = 'رفع ملفات للمريض'               WHERE name = 'Clinical.Files.Upload';
UPDATE permissions SET display_name = 'حذف ملفات المريض'               WHERE name = 'Clinical.Files.Delete';

UPDATE permissions SET display_name = 'عرض طلبات المختبر'              WHERE name = 'Lab.Orders.View';
UPDATE permissions SET display_name = 'إنشاء طلب مختبر'               WHERE name = 'Lab.Orders.Create';
UPDATE permissions SET display_name = 'تعديل طلب مختبر'               WHERE name = 'Lab.Orders.Edit';
UPDATE permissions SET display_name = 'حذف طلب مختبر'                  WHERE name = 'Lab.Orders.Delete';
UPDATE permissions SET display_name = 'طباعة طلب مختبر'               WHERE name = 'Lab.Orders.Print';
UPDATE permissions SET display_name = 'عرض نتائج المختبر'              WHERE name = 'Lab.Results.View';
UPDATE permissions SET display_name = 'إدخال نتائج المختبر'            WHERE name = 'Lab.Results.Edit';
UPDATE permissions SET display_name = 'عرض المختبرات الخارجية'         WHERE name = 'Lab.ExternalLabs.View';
UPDATE permissions SET display_name = 'إضافة مختبر خارجي'              WHERE name = 'Lab.ExternalLabs.Create';
UPDATE permissions SET display_name = 'تعديل مختبر خارجي'              WHERE name = 'Lab.ExternalLabs.Edit';

UPDATE permissions SET display_name = 'عرض طلبات الأشعة'               WHERE name = 'Radiology.Orders.View';
UPDATE permissions SET display_name = 'إنشاء طلب أشعة'                 WHERE name = 'Radiology.Orders.Create';
UPDATE permissions SET display_name = 'تعديل طلب أشعة'                 WHERE name = 'Radiology.Orders.Edit';
UPDATE permissions SET display_name = 'حذف طلب أشعة'                   WHERE name = 'Radiology.Orders.Delete';
UPDATE permissions SET display_name = 'طباعة طلب أشعة'                 WHERE name = 'Radiology.Orders.Print';
UPDATE permissions SET display_name = 'عرض صور الأشعة'                 WHERE name = 'Radiology.Images.View';
UPDATE permissions SET display_name = 'رفع صور أشعة'                   WHERE name = 'Radiology.Images.Upload';

UPDATE permissions SET display_name = 'مساحة الصراف'                   WHERE name = 'Financial.CashierDesk.View';
UPDATE permissions SET display_name = 'عرض الفواتير'                   WHERE name = 'Financial.Invoices.View';
UPDATE permissions SET display_name = 'إنشاء فاتورة'                   WHERE name = 'Financial.Invoices.Create';
UPDATE permissions SET display_name = 'تعديل فاتورة'                   WHERE name = 'Financial.Invoices.Edit';
UPDATE permissions SET display_name = 'حذف فاتورة'                     WHERE name = 'Financial.Invoices.Delete';
UPDATE permissions SET display_name = 'طباعة فاتورة'                   WHERE name = 'Financial.Invoices.Print';
UPDATE permissions SET display_name = 'تصدير فاتورة PDF'               WHERE name = 'Financial.Invoices.ExportPdf';
UPDATE permissions SET display_name = 'تأكيد فاتورة'                   WHERE name = 'Financial.Invoices.Confirm';
UPDATE permissions SET display_name = 'إلغاء فاتورة'                   WHERE name = 'Financial.Invoices.Cancel';
UPDATE permissions SET display_name = 'إصدار مرتجع'                    WHERE name = 'Financial.Invoices.Refund';
UPDATE permissions SET display_name = 'عرض الأقساط'                    WHERE name = 'Financial.Installments.View';
UPDATE permissions SET display_name = 'إنشاء خطة أقساط'               WHERE name = 'Financial.Installments.Create';
UPDATE permissions SET display_name = 'تعديل خطة أقساط'               WHERE name = 'Financial.Installments.Edit';
UPDATE permissions SET display_name = 'حذف خطة أقساط'                  WHERE name = 'Financial.Installments.Delete';
UPDATE permissions SET display_name = 'عرض المدفوعات'                  WHERE name = 'Financial.Payments.View';
UPDATE permissions SET display_name = 'تسجيل دفعة'                     WHERE name = 'Financial.Payments.Create';
UPDATE permissions SET display_name = 'حذف دفعة'                       WHERE name = 'Financial.Payments.Delete';
UPDATE permissions SET display_name = 'عرض الخزائن'                    WHERE name = 'Financial.Treasury.View';
UPDATE permissions SET display_name = 'إنشاء خزينة'                    WHERE name = 'Financial.Treasury.Create';
UPDATE permissions SET display_name = 'تعديل الخزينة'                  WHERE name = 'Financial.Treasury.Edit';
UPDATE permissions SET display_name = 'تحويل بين خزائن'                WHERE name = 'Financial.Treasury.Transfer';
UPDATE permissions SET display_name = 'عرض المصروفات'                  WHERE name = 'Financial.Expenses.View';
UPDATE permissions SET display_name = 'إضافة مصروف'                    WHERE name = 'Financial.Expenses.Create';
UPDATE permissions SET display_name = 'تعديل مصروف'                    WHERE name = 'Financial.Expenses.Edit';
UPDATE permissions SET display_name = 'حذف مصروف'                      WHERE name = 'Financial.Expenses.Delete';
UPDATE permissions SET display_name = 'تصدير مصروفات PDF'              WHERE name = 'Financial.Expenses.ExportPdf';
UPDATE permissions SET display_name = 'تصدير مصروفات Excel'            WHERE name = 'Financial.Expenses.ExportExcel';
UPDATE permissions SET display_name = 'حسابات الأطباء - عرض'          WHERE name = 'Financial.Doctors.View';
UPDATE permissions SET display_name = 'حسابات الأطباء - تعديل'        WHERE name = 'Financial.Doctors.Edit';

UPDATE permissions SET display_name = 'عرض شركات التأمين'              WHERE name = 'Insurance.Companies.View';
UPDATE permissions SET display_name = 'إضافة شركة تأمين'               WHERE name = 'Insurance.Companies.Create';
UPDATE permissions SET display_name = 'تعديل شركة تأمين'               WHERE name = 'Insurance.Companies.Edit';
UPDATE permissions SET display_name = 'حذف شركة تأمين'                 WHERE name = 'Insurance.Companies.Delete';
UPDATE permissions SET display_name = 'عرض المطالبات'                  WHERE name = 'Insurance.Claims.View';
UPDATE permissions SET display_name = 'إنشاء مطالبة'                   WHERE name = 'Insurance.Claims.Create';
UPDATE permissions SET display_name = 'تعديل مطالبة'                   WHERE name = 'Insurance.Claims.Edit';
UPDATE permissions SET display_name = 'حذف مطالبة'                     WHERE name = 'Insurance.Claims.Delete';
UPDATE permissions SET display_name = 'طباعة مطالبة'                   WHERE name = 'Insurance.Claims.Print';
UPDATE permissions SET display_name = 'تصدير مطالبات PDF'              WHERE name = 'Insurance.Claims.ExportPdf';
UPDATE permissions SET display_name = 'اعتماد مطالبة'                  WHERE name = 'Insurance.Claims.Approve';
UPDATE permissions SET display_name = 'إلغاء مطالبة'                   WHERE name = 'Insurance.Claims.Cancel';
UPDATE permissions SET display_name = 'عرض مستحقات التأمين'            WHERE name = 'Insurance.Receivables.View';

UPDATE permissions SET display_name = 'عرض الأصناف'                    WHERE name = 'Inventory.Items.View';
UPDATE permissions SET display_name = 'إضافة صنف'                      WHERE name = 'Inventory.Items.Create';
UPDATE permissions SET display_name = 'تعديل صنف'                      WHERE name = 'Inventory.Items.Edit';
UPDATE permissions SET display_name = 'حذف صنف'                        WHERE name = 'Inventory.Items.Delete';
UPDATE permissions SET display_name = 'تصدير الأصناف Excel'            WHERE name = 'Inventory.Items.ExportExcel';
UPDATE permissions SET display_name = 'عرض حركات المخزون'              WHERE name = 'Inventory.Movements.View';
UPDATE permissions SET display_name = 'تسجيل حركة مخزون'              WHERE name = 'Inventory.Movements.Create';
UPDATE permissions SET display_name = 'عرض الجرد'                      WHERE name = 'Inventory.Stocktake.View';
UPDATE permissions SET display_name = 'إنشاء جرد'                      WHERE name = 'Inventory.Stocktake.Create';
UPDATE permissions SET display_name = 'عرض تنبيهات المخزون'            WHERE name = 'Inventory.Alerts.View';

UPDATE permissions SET display_name = 'عرض الموردين'                   WHERE name = 'Purchasing.Suppliers.View';
UPDATE permissions SET display_name = 'إضافة مورد'                     WHERE name = 'Purchasing.Suppliers.Create';
UPDATE permissions SET display_name = 'تعديل مورد'                     WHERE name = 'Purchasing.Suppliers.Edit';
UPDATE permissions SET display_name = 'عرض أوامر الشراء'               WHERE name = 'Purchasing.Orders.View';
UPDATE permissions SET display_name = 'إنشاء أمر شراء'                 WHERE name = 'Purchasing.Orders.Create';
UPDATE permissions SET display_name = 'تعديل أمر شراء'                 WHERE name = 'Purchasing.Orders.Edit';
UPDATE permissions SET display_name = 'حذف أمر شراء'                   WHERE name = 'Purchasing.Orders.Delete';
UPDATE permissions SET display_name = 'اعتماد أمر شراء'                WHERE name = 'Purchasing.Orders.Approve';
UPDATE permissions SET display_name = 'طباعة أمر شراء'                 WHERE name = 'Purchasing.Orders.Print';
UPDATE permissions SET display_name = 'عرض فواتير الشراء'              WHERE name = 'Purchasing.Invoices.View';
UPDATE permissions SET display_name = 'إنشاء فاتورة شراء'              WHERE name = 'Purchasing.Invoices.Create';
UPDATE permissions SET display_name = 'تعديل فاتورة شراء'              WHERE name = 'Purchasing.Invoices.Edit';
UPDATE permissions SET display_name = 'حذف فاتورة شراء'                WHERE name = 'Purchasing.Invoices.Delete';
UPDATE permissions SET display_name = 'طباعة فاتورة شراء'              WHERE name = 'Purchasing.Invoices.Print';
UPDATE permissions SET display_name = 'تصدير فاتورة شراء PDF'          WHERE name = 'Purchasing.Invoices.ExportPdf';
UPDATE permissions SET display_name = 'عرض مرتجعات الشراء'             WHERE name = 'Purchasing.Returns.View';
UPDATE permissions SET display_name = 'إنشاء مرتجع شراء'               WHERE name = 'Purchasing.Returns.Create';

UPDATE permissions SET display_name = 'عرض الأصول الثابتة'             WHERE name = 'Assets.Assets.View';
UPDATE permissions SET display_name = 'إضافة أصل ثابت'                 WHERE name = 'Assets.Assets.Create';
UPDATE permissions SET display_name = 'تعديل أصل ثابت'                 WHERE name = 'Assets.Assets.Edit';
UPDATE permissions SET display_name = 'حذف أصل ثابت'                   WHERE name = 'Assets.Assets.Delete';
UPDATE permissions SET display_name = 'طباعة سجل الأصول'               WHERE name = 'Assets.Assets.Print';
UPDATE permissions SET display_name = 'عرض سجل الصيانة'                WHERE name = 'Assets.Maintenance.View';
UPDATE permissions SET display_name = 'تسجيل صيانة'                    WHERE name = 'Assets.Maintenance.Create';
UPDATE permissions SET display_name = 'عرض فئات الأصول'                WHERE name = 'Assets.Categories.View';
UPDATE permissions SET display_name = 'إضافة فئة أصول'                 WHERE name = 'Assets.Categories.Create';
UPDATE permissions SET display_name = 'تعديل فئة أصول'                 WHERE name = 'Assets.Categories.Edit';

UPDATE permissions SET display_name = 'التقارير المالية - عرض'         WHERE name = 'Reports.Financial.View';
UPDATE permissions SET display_name = 'التقارير المالية - طباعة'       WHERE name = 'Reports.Financial.Print';
UPDATE permissions SET display_name = 'التقارير المالية - PDF'         WHERE name = 'Reports.Financial.ExportPdf';
UPDATE permissions SET display_name = 'التقارير المالية - Excel'       WHERE name = 'Reports.Financial.ExportExcel';
UPDATE permissions SET display_name = 'التقارير التشغيلية - عرض'       WHERE name = 'Reports.Operational.View';
UPDATE permissions SET display_name = 'التقارير التشغيلية - طباعة'     WHERE name = 'Reports.Operational.Print';
UPDATE permissions SET display_name = 'التقارير التشغيلية - PDF'       WHERE name = 'Reports.Operational.ExportPdf';
UPDATE permissions SET display_name = 'التقارير التشغيلية - Excel'     WHERE name = 'Reports.Operational.ExportExcel';
UPDATE permissions SET display_name = 'تقارير المشتريات - عرض'         WHERE name = 'Reports.Purchasing.View';
UPDATE permissions SET display_name = 'تقارير المشتريات - طباعة'       WHERE name = 'Reports.Purchasing.Print';
UPDATE permissions SET display_name = 'تقارير المشتريات - PDF'         WHERE name = 'Reports.Purchasing.ExportPdf';
UPDATE permissions SET display_name = 'تقارير المخزون - عرض'           WHERE name = 'Reports.Inventory.View';
UPDATE permissions SET display_name = 'تقارير المخزون - طباعة'         WHERE name = 'Reports.Inventory.Print';
UPDATE permissions SET display_name = 'تقرير تقادم الذمم - عرض'        WHERE name = 'Reports.ARaging.View';
UPDATE permissions SET display_name = 'تقرير تقادم الذمم - PDF'        WHERE name = 'Reports.ARaging.ExportPdf';
UPDATE permissions SET display_name = 'تقرير التحصيلات - عرض'          WHERE name = 'Reports.Collections.View';
UPDATE permissions SET display_name = 'تقرير التحصيلات - PDF'          WHERE name = 'Reports.Collections.ExportPdf';

UPDATE permissions SET display_name = 'عرض المستخدمين'                 WHERE name = 'IAM.Users.View';
UPDATE permissions SET display_name = 'إنشاء مستخدم'                   WHERE name = 'IAM.Users.Create';
UPDATE permissions SET display_name = 'تعديل مستخدم'                   WHERE name = 'IAM.Users.Edit';
UPDATE permissions SET display_name = 'حذف مستخدم'                     WHERE name = 'IAM.Users.Delete';
UPDATE permissions SET display_name = 'عرض الأدوار والصلاحيات'         WHERE name = 'IAM.Roles.View';
UPDATE permissions SET display_name = 'إنشاء دور'                      WHERE name = 'IAM.Roles.Create';
UPDATE permissions SET display_name = 'تعديل دور'                      WHERE name = 'IAM.Roles.Edit';
UPDATE permissions SET display_name = 'حذف دور'                        WHERE name = 'IAM.Roles.Delete';
UPDATE permissions SET display_name = 'عرض إعدادات النظام'             WHERE name = 'IAM.Settings.View';
UPDATE permissions SET display_name = 'تعديل إعدادات النظام'           WHERE name = 'IAM.Settings.Edit';
UPDATE permissions SET display_name = 'عرض الخدمات'                    WHERE name = 'IAM.Services.View';
UPDATE permissions SET display_name = 'إضافة خدمة'                     WHERE name = 'IAM.Services.Create';
UPDATE permissions SET display_name = 'تعديل خدمة'                     WHERE name = 'IAM.Services.Edit';
UPDATE permissions SET display_name = 'حذف خدمة'                       WHERE name = 'IAM.Services.Delete';
UPDATE permissions SET display_name = 'عرض إعداد الخزائن'              WHERE name = 'IAM.Vaults.View';
UPDATE permissions SET display_name = 'إضافة خزينة'                    WHERE name = 'IAM.Vaults.Create';
UPDATE permissions SET display_name = 'تعديل خزينة'                    WHERE name = 'IAM.Vaults.Edit';
UPDATE permissions SET display_name = 'عرض إعداد الأطباء'              WHERE name = 'IAM.Doctors.View';
UPDATE permissions SET display_name = 'إضافة طبيب'                     WHERE name = 'IAM.Doctors.Create';
UPDATE permissions SET display_name = 'تعديل طبيب'                     WHERE name = 'IAM.Doctors.Edit';
UPDATE permissions SET display_name = 'عرض إعداد التأمين'              WHERE name = 'IAM.Insurance.View';
UPDATE permissions SET display_name = 'إضافة شركة تأمين (إعدادات)'    WHERE name = 'IAM.Insurance.Create';

COMMIT;
